package tomeko.legacyskyblock.tooltip

enum class NBTTypes(
    val nbtId: String,
    val nbtName: String
) {
    ABILITY_SCROLL("ability_scroll", "Ability Scroll"),
    ADDITIONAL_COINS("additional_coins", "Additional Coins"),
    ANVIL_UI_BLOCK_DROP("AnvilUIBlockDrop", "Anvil UI Block Drop"),
    ART_OF_WAR_COUNT("art_of_war_count", "Art of War Count"),
    ATTRIBUTES("attributes", "Attributes"),
    AUCTION("auction", "Auction"),
    BASE_STAT_BOOST_PERCENTAGE("baseStatBoostPercentage", "Base Stat Boost Percentage"),
    BID("bid", "Bid"),
    BINGO_EVENT("bingo_event", "Bingo Event"),
    BOOKWORM_BOOKS("bookworm_books", "Bookworm Books"),
    BOSS_TIER("boss_tier", "Boss Tier"),
    BOOSTERS("boosters", "Boosters"),
    CAKE_OWNER("cake_owner", "Cake Owner"),
    CAPTURED_DATE("captured_date", "Captured Date"),
    CAPTURED_PLAYER("captured_player", "Captured Player"),
    CENTURY_YEAR("century_year", "Century Year"),
    CENTURY_YEAR_OBTAINED("century_year_obtained", "Century Year Obtained"),
    COLOR("color", "Color"),
    COLOR_INDEX("color_index", "Color Index"),
    DATE("date", "Date"),
    DEAD_CATS_FOUND("dead_cats_found", "Dead Cats Found"),
    DIVAN_POWDER_COATING("divan_powder_coating", "Divan Powder Coating"),
    DONATED_MUSEUM("donated_museum", "Donated Museum"),
    DRILL_FUEL("drill_fuel", "Drill Fuel"),
    DRILL_PART_ENGINE("drill_part_engine", "Drill Part Engine"),
    DRILL_PART_FUEL_TANK("drill_part_fuel_tank", "Drill Part Fuel Tank"),
    DRILL_PART_UPGRADE_MODULE("drill_part_upgrade_module", "Drill Part Upgrade Module"),
    DUNGEON_ITEM("dungeon_item", "Dungeon Item"),
    DUNGEON_ITEM_LEVEL("dungeon_item_level", "Dungeon Item Level"),
    EDITION("edition", "Edition"),
    EFFECTS("effects", "Effects"),
    ENCHANTMENTS("enchantments", "Enchantments"),
    ENHANCED("enhanced", "Enhanced"),
    ENGINE("engine", "Engine"),
    ETHERMERGE("ethermerge", "Ethermerge"),
    EVENT("event", "Event"),
    EXTENDED("extended", "Extended"),
    FARMING_FOR_DUMMIES_COUNT("farming_for_dummies_count", "Farming for Dummies Count"),
    FUEL_TANK("fuel_tank", "Fuel Tank"),
    FUNGI_CUTTER_MODE("fungi_cutter_mode", "Fungi Cutter Mode"),
    GEMSTONES("gems", "Gemstones"),
    GILDED_GIFTED_COINS("gilded_gifted_coins", "Gilded Gifted Coins"),
    HISTORIC_DUNGEON_SCORE("historic_dungeon_score", "Historic Dungeon Score"),
    HOOK("hook", "Hook"),
    HOT_POTATO_COUNT("hot_potato_count", "Hot Potato Count"),
    ID("id", "ID"),
    INITIATOR_PLAYER("initiator_player", "Initiator Player"),
    KUUDRA_CAVITY_RARITY("kuudraCavityRarity", "Kuudra Cavity Rarity"),
    LAVA_CREATURES_KILLED("lava_creatures_killed", "Lava Creatures Killed"),
    LEADERBOARD_PLAYER("leaderboard_player", "Leaderboard Player"),
    LEADERBOARD_POSITION("leaderboard_position", "Leaderboard Position"),
    LEADERBOARD_SCORE("leaderboard_score", "Leaderboard Score"),
    LEVELABLE_EXP("levelable_exp", "Levelable Experience"),
    LEVELABLE_LVL("levelable_lvl", "Levelable Level"),
    LEVELABLE_OVERCLOCKS("levelable_overclocks", "Levelable Overclocks"),
    LEVELS_FOUND("levels_found", "Levels Found"),
    LINE("line", "Line"),
    LM_EVO("lm_evo", "LM Evo"),
    LOGS_CUT("logs_cut", "Logs Cut"),
    MANA_DISINTEGRATOR_COUNT("mana_disintegrator_count", "Mana Disintegrator Count"),
    MINED_CROPS("mined_crops", "Mined Crops"),
    MODIFIER("modifier", "Modifier"),
    NAMES_FOUND("names_found", "Names Found"),
    NEW_YEARS_CAKE("new_years_cake", "New Year's Cake"),
    ORIGIN_TAG("originTag", "Origin Tag"),
    PARTY_HAT_COLOR("party_hat_color", "Party Hat Color"),
    PARTY_HAT_EMOJI("party_hat_emoji", "Party Hat Emoji"),
    PARTY_HAT_YEAR("party_hat_year", "Party Hat Year"),
    PERSONAL_COMPACT_NUMBER("personal_compact_\\d+", "Personal Compact Number"),
    PERSONAL_DELETOR_ACTIVE("PERSONAL_DELETOR_ACTIVE", "Personal Deletor Active"),
    PERSONAL_DELETOR_NUMBER("personal_deletor_\\d+", "Personal Deletor Number"),
    PET_INFO("petInfo", "Pet Info"),
    PICKONIMBUS_DURABILITY("pickonimbus_durability", "Pickonimbus Durability"),
    PLAYER("player", "Player"),
    PLAYTIME("playtime", "Playtime"),
    POLARVOID("polarvoid", "Polarvoid"),
    POTION("potion", "Potion"),
    POTION_LEVEL("potion_level", "Potion Level"),
    POTION_TYPE("potion_type", "Potion Type"),
    POWER_ABILITY_SCROLL("power_ability_scroll", "Power Ability Scroll"),
    RAFFLE_WIN("raffle_win", "Raffle Win"),
    RAFFLE_YEAR("raffle_year", "Raffle Year"),
    RARITY_UPGRADES("rarity_upgrades", "Rarity Upgrades"),
    RECIPIENT_ID("recipient_id", "Recipient ID"),
    RECIPIENT_NAME("recipient_name", "Recipient Name"),
    RECIPIENT_TEAM("recipient_team", "Recipient Team"),
    RIFT_TRANSFERRED("rift_transferred", "Rift Transferred"),
    SHOWN_TO_CORAL("shown_to_coral", "Shown to Coral"),
    SINKER("sinker", "Sinker"),
    SKILL_REQ("\\w+_skill_req", "Skill Requirement"),
    SOUL_DURABILITY("soul_durability", "Soul Durability"),
    SOULBOUND("soulbound", "Soulbound"),
    SPRAY("spray", "Spray"),
    SPRAY_ITEM("spray_item", "Spray Item"),
    STACKING_ENCHANTMENT(
        ".*(?:^|_)(expertise|compact|cultivating|absorb|champion|hecatomb|toxophilite)(?:_|$).*",
        "Stacking Enchantment"
    ),
    STATS_BOOK("stats_book", "Stats Book"),
    TALISMAN_ENRICHMENT("talisman_enrichment", "Talisman Enrichment"),
    TD_ATTUNE_MODE("td_attune_mode", "TD Attune Mode"),
    TICKETS("tickets", "Tickets"),
    TIMESTAMP("timestamp", "Timestamp"),
    TRAPS_DEFUSED("trapsDefused", "Traps Defused"),
    TUNED_TRANSMISSION("tuned_transmission", "Tuned Transmission"),
    UPGRADE_LEVEL("upgrade_level", "Upgrade Level"),
    UPGRADE_MODULE("upgrade_module", "Upgrade Module"),
    UPGRADED_RARITY("upgradedRarity", "Upgraded Rarity"),
    UUID("uuid", "UUID"),
    VACUUMED_MOSQUITO("vacuumed_mosquito", "Vacuumed Mosquito"),
    VACUUMED_SILVERFISH("vacuumed_silverfish", "Vacuumed Silverfish"),
    VACUUMED_SPIDER("vacuumed_spider", "Vacuumed Spider"),
    WATER_LEVEL("water_level", "Water Level"),
    WET_BOOK_COUNT("wet_book_count", "Wet Book Count"),
    WINNING_BID("winning_bid", "Winning Bid"),
    WINNING_TEAM("winning_team", "Winning Team"),
    WOOD_SINGULARITY_COUNT("wood_singularity_count", "Wood Singularity Count"),
    YEAR("year", "Year"),
    YEAR_OBTAINED("yearObtained", "Year Obtained"),

    OTHER("", "Other");

    companion object {
        fun fromId(id: String): NBTTypes = entries.firstOrNull { it != OTHER && Regex(it.nbtId).matches(id) } ?: OTHER
    }
}